services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - ".:/simple_chat"
      - assets:/simple_chat/public/assets
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # redis:
  #   image: redis
  #   volumes:
  #     - redis_data:/data

volumes:
  pg_data: {}
  assets:
  gems:
