services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - ".:/simple_chat"
      - assets:/simple_chat/public/assets
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  assets:
  gems:
  pg_data:
  redis_data:
