services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - app-storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # redis:
  #   image: redis
  #   volumes:
  #     - redis_data:/data

volumes:
  app-storage: {}
  pg_data: {}
