default: &default
  adapter: postgresql
  encoding: unicode
  username:  root
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432

development:
  <<: *default
  database: simple_chat

test:
  <<: *default
  database: simple_chat_test

production:
  <<: *default
  database: simple_chat
